class Product {
  final int id;
  final String name;
  final String description;
  final String image;
  final double price;
  final String brand;
  final String processor;
  final String ram;
  final String storage;
  final String display;
  final int article;
  bool isFavorite;
  Product({
    required this.id,
    required this.name,
    required this.description,
    required this.image,
    required this.price,
    required this.brand,
    required this.processor,
    required this.ram,
    required this.storage,
    required this.display,
    required this.article,
    this.isFavorite = false,
  });
}

final List<Product> products = [
  Product(
    id: 1,
    name: 'Ноутбук HONOR MagicBook 15 15.6',
    description: 'Компактный, но мощный ноутбук Honor MagicBook 15 R5/8/512 отлично подойдёт для повседневных и рабочих задач. Не относится к игровым моделям, но удобен для стандартного использования в офисе или дома. без лишних деталей Лаконичный дизайн оценят любители минимализма.',
    image: 'assets/image1.png',
    price: 35010,
    brand: 'HONOR',
    processor: 'AMD Ryzen 5 5500U',
    ram: '8 ГБ',
    storage: '512 ГБ',
    display: '15.6"',
    article: 521234,
  ),
  Product(
    id: 2,
    name: 'Digma Ноутбук Pro Breve DN15R7-ADXW01 Silver 15.6',
    description: 'Тип товара: Ноутбук; Тип оборудования: Ноутбук; Серия: Pro; Модель: Breve DN15R7-ADXW01; Операционная система: Windows 11 Pro; Цвет корпуса: серебристый; Цвет крышки ноутбука: серебристый; Цвет клавиш ноутбука: черный; Процессор ноутбука: AMD Ryzen 7; Модель процессора: 5700U; Частота процессора, ГГц: 1,8; Максимальная частота процессора, ГГц: 4,3; Размер L2 кэша (МБ): 4; Количество ядер: 8; Тип видеокарты: встроенная; Видеокарта: AMD Radeon Vega 8; Объем дискретной видеопамяти (ГБ): 0; Видеопамять: Выделяемая из оперативной; Поддержка карт памяти: Есть; Типы поддерживаемых карт: microSD; Объем жесткого диска (ГБ): 0; Объем жесткого диска SSD (ГБ): 512;',
    image: 'assets/image2.png',
    price: 41370,
    brand: 'Digma',
    processor: 'AMD Ryzen 7 5700U',
    ram: '16 ГБ',
    storage: '512 ГБ',
    display: '15.6"',
    article: 234560,
  ),
  Product(
    id: 3,
    name: 'Ноутбук Asus VivoBook E1504FA-BQ664, 15.6',
    description: 'Ноутбук Asus VivoBook E1504FA-BQ664, 15.6", IPS, AMD Ryzen 5 7520U, LPDDR5 16ГБ, SSD 512ГБ, AMD Radeon, черный (90nb0zr2-m012z0)',
    image: 'assets/image3.png',
    price: 48681,
    brand: 'Asus',
    processor: 'AMD Ryzen 5 7520U',
    ram: '16ГБ',
    storage: '512 ГБ',
    display: '15.6"',
    article: 234521,
  ),
  Product(
    id: 4,
    name: 'Ноутбук игровой MSI Katana 17/17.3',
    description: 'Ноутбук игровой MSI Katana GF76 B12UCR-1024XRU с экраном диагональю 17,3 дюйма выполнен в пластиковом корпусе габаритами 398х25,2х273 мм и весом около 2,6 кг. За быстродействие и стабильную работу устройства отвечают восьмиядерный процессор Intel Core i5 12450H (2,0-4,4 ГГц) с кэш-памятью третьего уровня 12 Гб и дискретная видеокарта GeForce RTX 3050. Размер оперативной памяти ноутбука — 8 Гб, емкость SSD накопителя — 512 Гб. Поддерживаются все модели беспроводных геймпадов, алгоритмы искусственного интеллекта, трассировка лучей в режиме реального времени.',
    image: 'assets/image4.png',
    price: 79990,
    brand: 'MSI',
    processor: 'Intel Core i5 12450H',
    ram: '8 ГБ',
    storage: '512 ГБ',
    display: '17.3"',
    article: 563179,
  ),
  Product(
    id: 5,
    name: 'Ноутбук Honor MagicBook NMH-WFP9HN, 14',
    description: 'Ноутбук Honor MagicBook NMH-WFP9HN - это современное и функциональное устройство, которое станет незаменимым помощником в работе и учебе. Ноутбук оснащен 8-ядерным процессором AMD Ryzen 7 5700U с частотой 1.8 ГГц, что обеспечивает высокую производительность и быстродействие. Объем оперативной памяти составляет 16 ГБ, что позволяет комфортно работать с несколькими приложениями одновременно. Устройство оснащено встроенной видеокартой AMD Radeon, что гарантирует качественное и плавное воспроизведение видео и графики.',
    image: 'assets/image5.png',
    price: 49990,
    brand: 'Honor',
    processor: 'AMD Ryzen 7 5700U',
    ram: '16 ГБ',
    storage: '512 ГБ',
    display: '14"',
    article: 152783,
  ),
  Product(
    id: 6,
    name: 'Ноутбук HUAWEI MateBook D 16/16',
    description: 'Ноутбук Huawei MateBook D 16 (53013WXE), цвет космический серый под управлением ОС Windows 11 Home предназначен для решения универсальных пользовательских задач, работы с графической документацией, мультимедиа, нетребовательных онлайн-игр. Устройство в корпусе из алюминиевого сплава габаритами 357х249х18,4 мм (ширина/высота/глубина) и весом около 1,7 кг функционирует на базе восьмиядерного процессора Intel Core i5 12450H (2,0-4,4 ГГц) и видеоядра Intel UHD Graphics. Емкость SSD накопителя — 512 Гб, размер оперативной памяти — 8 Гб.',
    image: 'assets/image6.png',
    price: 69990,
    brand: 'HUAWEI',
    processor: 'Intel Core i5 12450H',
    ram: '8 ГБ',
    storage: '512 ГБ',
    display: '16"',
    article: 82123,
  ),
  Product(
    id: 7,
    name: 'Ноутбук 15.6, ультрабук для работы и учебы',
    description: 'Ноутбук 15.6" ультрабук с процессором Intel J4125 и SSD-диском на 512 Гб - это идеальное решение для тех, кто ищет мощный и компактный ноутбук для работы и повседневных задач. Он оснащен операционной системой Windows 10 Pro, русским интерфейсом клавиатуры, а также имеет встроенную видеокарту Intel UHD Graphics 600 и оперативную память DDR4 на 8 Гб.',
    image: 'assets/image7.png',
    price: 19990,
    brand: 'Intel',
    processor: 'Intel J4125',
    ram: '8 ГБ',
    storage: '512 ГБ',
    display: '15.6"',
    article: 234687,
  ),
  Product(
    id: 8,
    name: 'Ноутбук игровой ASUS TUF Gaming A15 FA507NUR-LP044 90NR0JP5-M002D0, 15.6',
    description: 'Ноутбук ASUS TUF Gaming A15 с 15.6-дюймовым IPS дисплеем в стильном сером корпусе — это идеальное решение для тех, кто ищет высокую производительность и отличное качество изображения. IPS-технология обеспечивает яркие цвета и широкие углы обзора, что делает каждую игровую сессию более захватывающей.',
    image: 'assets/image8.png',
    price: 79990,
    brand: 'ASUS',
    processor: 'AMD Ryzen 7 7435HS',
    ram: '16 ГБ',
    storage: '512 ГБ',
    display: '15.6"',
    article: 929345,
  ),
  Product(
    id: 9,
    name: 'Ноутбук Apple MacBook Pro A2780 MNW93C/A, 16.2',
    description: 'Ноутбук Apple MacBook Pro A2780 имеет 16,2-дюймовый дисплей на базе фирменной IPS-матрицы Retina с углами обзора 178 градусов, на котором удобно работать в многооконном режиме (например, можно редактировать PDF-файл или создавать презентацию и параллельно общаться в мессенджере, не сворачивая открытые «окна»). За счет сверхвысокого разрешения 3456х2234 пикселей и увеличенной частоты обновления 120 Гц картинка выглядит четкой и детализированной в любых сценариях использования, а также не размывается при отображении анимаций и в динамичных сценах, поэтому глаза не будут перенапрягаться при длительной работе за экраном.',
    image: 'assets/image9.png',
    price: 199990,
    brand: 'Apple',
    processor: 'Apple M2 Pro 12',
    ram: '16 ГБ',
    storage: '1 ТБ',
    display: '16.2"',
    article: 98124,
  ),
  Product(
    id: 10,
    name: '15.6" Ноутбук Xiaomi Redmi Book 15E',
    description: 'Xiaomi Redmi Book 15E (JYU4543CN) – надежный и производительный ноутбук для выполнения повседневных задач, работы и развлечений. Небольшой вес и компактный дизайн позволяет удобно носить устройство с собой и использовать в различных условиях. Черный цвет корпуса придает ноутбуку стильный и современный вид.',
    image: 'assets/image10.png',
    price: 48748,
    brand: 'Xiaomi',
    processor: 'Intel Core i7-11390H',
    ram: '16ГБ',
    storage: '512 ГБ',
    display: '15.6"',
    article: 551234,
  ),
];
